config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create] 
      resources :likes, only: [:create]
    end
  end

  namespace :api, :defaults => {:format => :json} do
    post 'login', to: 'authentication#authenticate'
    resources :users, only: [:index, :show] do
      resources :posts, only: [:index, :show] do
        resources :comments, only: [:index, :create] 
      end
    end
  end

  root "users#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :validatable, :confirmable

  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id
  has_many :posts, foreign_key: :author_id

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def as_json(_options = {})
    super(only: %i[id name bio posts_counter])
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  include ApiExceptionHandler
  before_action :authorize_request

  def index
    @users = User.all.order(created_at: :asc)
    render json: @users
  end

  def show
    @user = User.find(params[:id])
    render json: @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @current_user = current_user
    @users = User.all.order(created_at: :asc)
  end

  def show
    @current_user = current_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<ul class="flex flex-col gap-5">
  <% @users.each do |user| %>
    <li>
      <%= link_to user_path(user.id) do %>
        <%= render partial: "shared/user_info", locals: { user: user } %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="flex flex-col gap-5">
  <%= render partial: "shared/user_info", locals: { user: @user } %>

  <div class="border p-3">
    <h2 class="text-2xl">Bio</h2>
    <p class="mt-2"><%= @user.bio %></p>
  </div>

  <ul class="flex flex-col gap-5">
    <% @user.recent_posts.each do |post| %>
      <li>
        <%= link_to user_post_path(@user.id, post.id) do %>
          <%= render partial: "shared/post_info", locals: { post: post } %>
        <% end %>
      </li>
    <% end %>
  </ul>

  <%= link_to user_posts_path(@user.id), class: "self-center p-3 border" do %>
    See All Posts
  <% end %>
</div>