config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create] 
      resources :likes, only: [:create]
    end
  end

  namespace :api, :defaults => {:format => :json} do
    post 'login', to: 'authentication#authenticate'
    resources :users, only: [:index, :show] do
      resources :posts, only: [:index, :show] do
        resources :comments, only: [:index, :create] 
      end
    end
  end

  root "users#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  after_save :update_author_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :text, presence: true
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def as_json(_options = {})
    super(only: %i[id title text likes_counter comments_counter])
  end

  private

  def update_author_posts_counter
    author.update(posts_counter: author.posts.length)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  include ApiExceptionHandler
  before_action :authorize_request
  def index
    @user = User.find(params[:user_id])
    render json: @user.posts
  end

  def show
    @post = Post.find_by(id: params[:id], author_id: params[:user_id])
    raise ActiveRecord::RecordNotFound, 'Wrong post or user id' if @post.nil?

    render json: @post
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @current_user = current_user
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @current_user = current_user
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def new
    @current_user = current_user
    @post = Post.new
  end

  def create
    @current_user = current_user
    post = Post.new(post_params.merge(author_id: @current_user.id))
    if post.save
      redirect_to user_path(@current_user.id), notice: 'Post published'
    else
      redirect_to new_user_post_path(@current_user.id), alert: post.errors.full_messages
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div class="flex flex-col gap-5">
  <%= render partial: "shared/user_info", locals: { user: @user } %>
  <ul class="flex flex-col gap-5">
    <% @posts.each do |post| %>
      <li>
        <%= link_to user_post_path(@user.id, post.id) do %>
          <%= render partial: "shared/post_info", locals: { post: post } %>
        <% end %>
        <%= render partial: "shared/comments", locals: { comments: post.recent_comments } %>
      </li>
    <% end %>
  </ul>
</div>

app/views/posts/new.html.erb
<%= form_with model: @post, url: user_posts_path do |f| %>
  <div class="border p-3 flex flex-col gap-3">
    <h1 class="text-3xl">Create a new post</h1>
    <div>
      <%= f.label :title, "Title" %>
      <%= f.text_field :title, class: "w-full p-2 border" %>
    </div>
    <div>
      <%= f.label :text, "Text" %>
      <%= f.text_area :text, class: "w-full p-2 border" %>
    </div>
    <%= f.submit "Publish", class: "self-end py-2 px-3 border rounded-xl" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="flex flex-col gap-5">
  <article class="border flex flex-col p-3 gap-3">
    <div class="flex justify-between items-baseline">
      <h1 class="text-2xl"><%= @post.title %> by <%= @post.author.name %></h1>
      <p class="text-sm">
        <%= "Comments: #{@post.comments_counter || 0}, Likes: #{@post.likes_counter || 0 }" %>
      </p>
    </div>
    <p><%= @post.text %></p>
    <div class="flex justify-end">
      <%= button_to user_post_likes_path(@post.author.id, @post.id), method: :post, class: "py-2 px-3 border rounded-xl" do %>
        Like
      <% end %>
    </div>
  </article>

  <%= render partial: "shared/comments", locals: { comments: @post.comments } %>

  <div class="flex justify-end">
    <%= link_to new_user_post_comment_path(@post.author.id, @post.id), class: "py-2 px-3 border rounded-xl" do %>
      Post a comment
    <% end %>
  </div>
</div>